// <auto-generated />
namespace MondayAssesment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dept_Stored_Proc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dept_Stored_Proc));
        
        string IMigrationMetadata.Id
        {
            get { return "202208290445281_Dept_Stored_Proc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
