//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Register
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Username is Required")]
        [MaxLength(length:20,ErrorMessage ="Maximum Username length should be 20")]
        public string Username { get; set; }

        public string Password { get; set; }

        [NotMapped]
        [Compare("Password",ErrorMessage ="Password and Confirm Password Should be Same")]
        public string CnfPassword { get; set; }

        [RegularExpression("^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$",ErrorMessage ="Enter Valid Email Id")]
        public string Email { get; set; }

        [RegularExpression("^[a-zA-Z]+[a-zA-Z]*$",ErrorMessage ="Enter Valid City.It should not contain Numeric value")]
        public string City { get; set; }
    }
}
